### ISSUE TITLE
2.0 should check for 5.3 compatibility

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView-AZ-Filters#22]
Since it's using namespaces, we'll need to check for 5.3 to prevent ☠️🐛

**Comment by soulseekah** [comment]
The loader should handle this out of the box:

https://github.com/gravityview/GravityView-AZ-Filters/blob/2.0/gravityview-az-filters.php

See how we check for a namespaced class? If PHP doesn't support namespaces that will return false.
