### ISSUE TITLE
Filtering for two checkbox values don't work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView-AZ-Filters#23]
Assuming a checkbox field with multiple options:

![gv-checkboxes](https://user-images.githubusercontent.com/1222472/37738316-65b5878e-2d35-11e8-9d85-743e9a475a59.jpg)

Filtering like this:

![gv-checkboxes-adv](https://user-images.githubusercontent.com/1222472/37738330-6e5be2fc-2d35-11e8-8580-4f4872eff7fc.jpg)

Won't work:

![gv-check-view](https://user-images.githubusercontent.com/1222472/37738339-767b2ea2-2d35-11e8-88e1-794ff75fd4b7.jpg)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/544662150/13824/

Replicated here: http://gravityview.com.br/wp-admin/post.php?post=1878&action=edit

**Comment by soulseekah** [comment]
Why is this in AZ? Is AZ also factored into the issue? Or is it an Advanced Filters issue only?

**Comment by rafaehlers** [comment]
@soulseekah my bad, wrong repo :joy:

**Comment by soulseekah** [comment]
No problem, you can leave it here if you like.

**Comment by rafaehlers** [comment]
Ref: https://github.com/gravityview/GravityView-Advanced-Filter-Extension/issues/48
